import type { Metadata } from "next";
import { Vazirmatn as Sans } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const sans = Sans({ subsets: ["arabic"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="fa-IR">
      <body className={`${sans.variable} antialiased font-sans`}>
        {children}
      </body>
    </html>
  );
}
